from pymba import Vimba, Frame

with Vimba() as vimba:
    cam = vimba.camera(0)
    cam_interface = vimba.interface(0)
    cam_system = vimba.system()
    cam_interface.open()
    cam.open()
    print(cam.feature_names())
    print(cam_interface.feature_names())
    print(cam_system.feature_names())
    print('Ranges')
    feature = cam.feature('Width')
    print(feature.value)
    print(feature.range)
    feature = cam.feature('Height')
    print(feature.value)
    print(feature.range)
    feature = cam.feature('OffsetX')
    print(feature.value)
    print(feature.range)
    feature = cam.feature('OffsetY')
    print(feature.value)
    print(feature.range)
