# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_main(object):
    def setupUi(self, main):
        if not main.objectName():
            main.setObjectName(u"main")
        main.resize(1192, 752)
        self.centralwidget = QWidget(main)
        self.centralwidget.setObjectName(u"centralwidget")
        self.box_preview = QGroupBox(self.centralwidget)
        self.box_preview.setObjectName(u"box_preview")
        self.box_preview.setGeometry(QRect(10, 10, 601, 391))
        self.Btn_StartStopPreview = QPushButton(self.box_preview)
        self.Btn_StartStopPreview.setObjectName(u"Btn_StartStopPreview")
        self.Btn_StartStopPreview.setGeometry(QRect(20, 20, 75, 23))
        self.Btn_ResetCameraBtn = QPushButton(self.box_preview)
        self.Btn_ResetCameraBtn.setObjectName(u"Btn_ResetCameraBtn")
        self.Btn_ResetCameraBtn.setGeometry(QRect(20, 50, 75, 23))
        self.PreviewWidget = QLabel(self.box_preview)
        self.PreviewWidget.setObjectName(u"PreviewWidget")
        self.PreviewWidget.setGeometry(QRect(110, 20, 480, 360))
        self.PreviewWidget.setMinimumSize(QSize(0, 0))
        self.PreviewWidget.setBaseSize(QSize(640, 480))
        self.PreviewWidget.setMouseTracking(True)
        self.PreviewWidget.setFrameShape(QFrame.Panel)
        self.PreviewWidget.setPixmap(QPixmap(u"../../MATLAB/Contact-Angle-Measurement/untitled1.png"))
        self.PreviewWidget.setScaledContents(False)
        self.PreviewWidget.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.box_preview)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 80, 75, 23))
        self.pushButton_2 = QPushButton(self.box_preview)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(20, 110, 75, 23))
        self.label = QLabel(self.box_preview)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 150, 61, 16))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(630, 10, 551, 391))
        self.tableWidget = QTableWidget(self.groupBox)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 20, 531, 361))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 420, 291, 191))
        self.pushButton_3 = QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(20, 30, 75, 23))
        icon = QIcon()
        icon.addFile(u"up.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_4 = QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 60, 75, 23))
        icon1 = QIcon()
        icon1.addFile(u"down.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.lineEdit = QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(120, 60, 41, 23))
        self.pushButton_5 = QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(230, 60, 31, 23))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 30, 101, 16))
        self.comboBox = QComboBox(self.groupBox_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(170, 60, 51, 23))
        self.horizontalSlider = QSlider(self.groupBox_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(120, 90, 141, 22))
        self.horizontalSlider.setMaximum(50000)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(1000)
        self.pushButton_6 = QPushButton(self.groupBox_2)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(20, 90, 75, 23))
        self.pushButton_11 = QPushButton(self.groupBox_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(20, 130, 81, 23))
        self.pushButton_12 = QPushButton(self.groupBox_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(20, 160, 81, 23))
        self.pushButton_13 = QPushButton(self.groupBox_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(110, 160, 81, 23))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(310, 430, 641, 251))
        self.checkBox = QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(40, 140, 131, 17))
        self.checkBox_2 = QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(40, 100, 111, 17))
        self.checkBox_3 = QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(40, 180, 121, 17))
        self.spinBox = QSpinBox(self.groupBox_3)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(180, 180, 42, 22))
        self.comboBox_2 = QComboBox(self.groupBox_3)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(250, 100, 41, 22))
        self.comboBox_3 = QComboBox(self.groupBox_3)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(250, 140, 41, 22))
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 80, 47, 13))
        self.pushButton_7 = QPushButton(self.groupBox_3)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(20, 20, 75, 23))
        self.pushButton_8 = QPushButton(self.groupBox_3)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(20, 50, 75, 23))
        self.checkBox_4 = QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(390, 40, 191, 17))
        self.checkBox_5 = QCheckBox(self.groupBox_3)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(390, 60, 70, 17))
        self.lineEdit_2 = QLineEdit(self.groupBox_3)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(180, 100, 41, 22))
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(180, 80, 47, 13))
        self.lineEdit_3 = QLineEdit(self.groupBox_3)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(180, 140, 41, 22))
        self.groupBox_4 = QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(470, 170, 161, 71))
        self.radioButton = QRadioButton(self.groupBox_4)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(10, 20, 171, 17))
        self.radioButton_2 = QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(10, 40, 131, 17))
        self.radioButton_2.setChecked(True)
        self.lineEdit_4 = QLineEdit(self.groupBox_3)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(400, 120, 51, 20))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(460, 120, 47, 21))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(320, 120, 71, 21))
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(230, 180, 47, 21))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(990, 420, 191, 251))
        self.pushButton_9 = QPushButton(self.groupBox_5)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(20, 30, 75, 23))
        self.pushButton_10 = QPushButton(self.groupBox_5)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(20, 70, 75, 23))
        main.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(main)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1192, 21))
        main.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(main)
        self.statusbar.setObjectName(u"statusbar")
        main.setStatusBar(self.statusbar)

        self.retranslateUi(main)

        QMetaObject.connectSlotsByName(main)
    # setupUi

    def retranslateUi(self, main):
        main.setWindowTitle(QCoreApplication.translate("main", u"main", None))
        self.box_preview.setTitle(QCoreApplication.translate("main", u"Preview", None))
        self.Btn_StartStopPreview.setText(QCoreApplication.translate("main", u"Start", None))
        self.Btn_ResetCameraBtn.setText(QCoreApplication.translate("main", u"Reset", None))
        self.PreviewWidget.setText("")
        self.pushButton.setText(QCoreApplication.translate("main", u"Set ROI", None))
        self.pushButton_2.setText(QCoreApplication.translate("main", u"Reset ROI", None))
        self.label.setText(QCoreApplication.translate("main", u"Angle: 66.6\u00b0", None))
        self.groupBox.setTitle(QCoreApplication.translate("main", u"Data View", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("main", u"Magnet / Motor Control", None))
        self.pushButton_3.setText(QCoreApplication.translate("main", u" Jog up   ", None))
        self.pushButton_4.setText(QCoreApplication.translate("main", u" Jog down", None))
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("main", u"Pos", None))
        self.pushButton_5.setText(QCoreApplication.translate("main", u"Go", None))
        self.label_2.setText(QCoreApplication.translate("main", u"Manual Positioning", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("main", u"steps", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("main", u"mm", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("main", u"mT", None))

        self.pushButton_6.setText(QCoreApplication.translate("main", u"STOP", None))
        self.pushButton_11.setText(QCoreApplication.translate("main", u"Load Calib File", None))
        self.pushButton_12.setText(QCoreApplication.translate("main", u"Calibrate", None))
        self.pushButton_13.setText(QCoreApplication.translate("main", u"Save Calib File", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("main", u"Measurement Control", None))
        self.checkBox.setText(QCoreApplication.translate("main", u"Sweep Magnetic Field", None))
        self.checkBox_2.setText(QCoreApplication.translate("main", u"Sweep over Time", None))
        self.checkBox_3.setText(QCoreApplication.translate("main", u"Repeat Measurement", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("main", u"1", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("main", u"2", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("main", u"3", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("main", u"4", None))

        self.comboBox_3.setItemText(0, QCoreApplication.translate("main", u"1", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("main", u"2", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("main", u"3", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("main", u"4", None))

        self.label_3.setText(QCoreApplication.translate("main", u"Priority:", None))
        self.pushButton_7.setText(QCoreApplication.translate("main", u"Start", None))
        self.pushButton_8.setText(QCoreApplication.translate("main", u"Cancel", None))
        self.checkBox_4.setText(QCoreApplication.translate("main", u"Save Image for every datapoint", None))
        self.checkBox_5.setText(QCoreApplication.translate("main", u"CheckBox", None))
        self.label_4.setText(QCoreApplication.translate("main", u"Interval", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("main", u"Droplet Measurement Method", None))
        self.radioButton.setText(QCoreApplication.translate("main", u"Dynamic Drop Method", None))
        self.radioButton_2.setText(QCoreApplication.translate("main", u"Sessile Drop Method", None))
        self.lineEdit_4.setPlaceholderText("")
        self.label_5.setText(QCoreApplication.translate("main", u"ul", None))
        self.label_6.setText(QCoreApplication.translate("main", u"Liquid Amount:", None))
        self.label_7.setText(QCoreApplication.translate("main", u"Times", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("main", u"Data Control", None))
        self.pushButton_9.setText(QCoreApplication.translate("main", u"Save As ...", None))
        self.pushButton_10.setText(QCoreApplication.translate("main", u"Load", None))
    # retranslateUi